name: Node CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        os: [macOS-10.14, windows-2016, ubuntu-18.04]

    steps:
      - uses: actions/checkout@master
      - name: Use Node.js 10.x
        uses: actions/setup-node@v1
        with:
          version: 10.x
      - name: npm install, build, and test
        run: |
          yarn install
          yarn test
